[package]
name = "syncthreads"
version = "0.1.0"
edition = "2021"

[dependencies]
aligned-vec = "0.5.0"
crossbeam = "0.8.4"
equator = "0.2.1"
parking_lot_core = "0.9.10"

[dev-dependencies]
rayon = "1.10.0"
threadpool = "1.8.1"
threadpool_scope = "0.1.0"
core_affinity = "0.8.1"
